### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by laughedelic** [mangecoeur/preview-inline#1]
Could you please update the changelog? I'm interested in the progress of this plugin, but watching the repo and reading commits is rather inconvenient. It would be nice to read what has changed/fixed in each release when I see an update of the plugin in Atom.

**Comment by mangecoeur** [comment]
sure can do. At the moment the patches are very minor so I didn't bother. Hopefully some bigger features landing soon...

**Comment by laughedelic** [comment]
ok :+1:
