### ISSUE TITLE
pic preview in latex enviroment

### ISSUE THREAD

**Issue by tonylee2016** [mangecoeur/preview-inline#11]
Can you add this new feature.

the package has great potential, I bet it will be very popular if you add this new feature

**Comment by mangecoeur** [comment]
I assume you mean previewing Images in addition to formula?

**Comment by tonylee2016** [comment]
yes exactly.

**Comment by mangecoeur** [comment]
i will look into it. Image inclusion in LaTeX is more complicated than Markdown, but it should be possible to hack something for common use cases.

**Comment by tonylee2016** [comment]
great ! thx

**Comment by mangecoeur** [comment]
I know it's been a while, but I finally added basic support for `\includegraphics` . It currently is limited to previewing full and relative file paths - i.e. you have to write `\includegraphics{path/to/image.jpg`  - it can't automatically guess the file extension and it doesn't support the latex commands to set the base image path. But at least it works ;)

**Comment by mangecoeur** [comment]
Update - it now guesses the file extension, but still requires the folder path.

**Comment by mangecoeur** [comment]
Graphics path is now supported, closing
