### ISSUE TITLE
No result

### ISSUE THREAD

**Issue by pachevalier** [mangecoeur/preview-inline#14]
I've tried to use preview-inline but this doesn't return anything. Here is a screenshot of my result : 
 
![preview_inline](https://cloud.githubusercontent.com/assets/3227753/16380054/18956134-3c75-11e6-84fd-2476b43973f6.png)

I'm running Atom.io 1.8.0 with Debian testing.

**Comment by mangecoeur** [comment]
do you have language-pfm installed?

**Comment by pachevalier** [comment]
No ! I'll try and I tell you. Thank you for your answer.

**Comment by pachevalier** [comment]
Ok it works. Thank you very much !!!

**Comment by pierregodard** [comment]
I might be missing something obvious, but I'm trying to make this preview work on `markdown` and `latex` files without success as well. I'm running `Mac OSX 10.11.6` with Atom `1.9.7` and `preview-inline 1.0.5`. I also have `language-pfm` installed.

Disabling all the community packages i have installed except for:
```
├── language-latex@0.6.1
├── language-pfm@0.82.0
├── preview-inline@1.0.5
```
doesn't change the issue.
