### ISSUE TITLE
Style configuration

### ISSUE THREAD

**Issue by MatteoRagni** [mangecoeur/preview-inline#21]
It seems to be incompatible with atom Material theme, due to color assignment (color: transparent??).

Is it possible to add two options for background and foreground color?

thanks

**Comment by mangecoeur** [comment]
Sorry it's not working for you - could you maybe post a screenshot?  I pick the colours from the theme colour, which should in theory make sure it matches the theme look - but I haven't tested with non default themes.

**Comment by mangecoeur** [comment]
Ok, added a tweak to the style selection should fix this problem.
